---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 443, host: 4433}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[simple_web::default]
      - recipe[os-hardening]
      - recipe[ssh-hardening]
    verifier:
      inspec_tests:
        - https://github.com/chris-rock/acme-inspec-profile
    attributes: 
      apt:
        unattended_upgrades:
          allowed_origins: ["origin=Ubuntu,archive=xenial-security"]
